# Generated by Django 3.2.8 on 2021-11-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessManagement', '0005_auto_20211123_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinclub',
            name='user_level',
            field=models.IntegerField(choices=[(0, 'Applicant'), (1, 'Member'), (2, 'Officer'), (3, 'Owner')], default=0),
        ),
    ]
