# Generated by Django 3.2.8 on 2021-11-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessManagement', '0006_userinclub_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='club_session',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
