# Generated by Django 3.2.8 on 2021-12-08 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chessManagement', '0007_alter_club_name'),
        ('chessManagement', '0009_userintournament_is_co_organiser'),
    ]

    operations = [
    ]
