# Generated by Django 3.2.8 on 2021-12-13 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chessManagement', '0010_merge_20211208_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='game',
            name='start_date',
        ),
        migrations.AddField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chessManagement.tournament'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
