# Generated by Django 3.2.8 on 2021-12-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessManagement', '0011_alter_tournament_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
