# Generated by Django 3.2.8 on 2021-12-15 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chessManagement', '0011_auto_20211213_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Elimination'), (1, 'Single')])),
                ('tournament_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chessManagement.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chessManagement.stage')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chessManagement.group'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chessManagement.stage'),
        ),
        migrations.AddField(
            model_name='userintournament',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chessManagement.group'),
        ),
    ]
