# Generated by Django 3.2.8 on 2021-12-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessManagement', '0012_auto_20211215_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='tournament_in',
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(blank=True, choices=[(0, 'Draw'), (1, 'Player 1'), (2, 'Player 2')], default=None, max_length=8, null=True),
        ),
    ]
