# Generated by Django 3.2.8 on 2021-12-16 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chessManagement', '0013_alter_game_winner'),
        ('chessManagement', '0013_auto_20211216_1323'),
    ]

    operations = [
    ]
