# Generated by Django 3.2.8 on 2021-12-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessManagement', '0013_alter_tournament_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='deadline',
            field=models.DateField(null=True, verbose_name='Deadline'),
        ),
    ]
