# Generated by Django 3.2.8 on 2021-12-17 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chessManagement', '0013_auto_20211217_0316'),
        ('chessManagement', '0014_merge_0013_alter_game_winner_0013_auto_20211216_1323'),
    ]

    operations = [
    ]
