# Generated by Django 3.2.8 on 2021-12-17 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chessManagement', '0015_merge_20211217_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='tournament_in',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chessManagement.tournament'),
            preserve_default=False,
        ),
    ]
