# Generated by Django 3.2.8 on 2021-12-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessManagement', '0017_alter_club_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.TextField(primary_key=True, serialize=False, unique=True),
        ),
    ]
